version: '3.8'

services:
  transaction-app:
    build: .
    image: transaction:v1.0.0
    container_name: transaction-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/transactionhistory
    networks:
      - transaction-network
   # volumes:
    #  - mongodb-data:/app/uploads

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - transaction-network
    volumes:
      - mongodb-data:/data/db

networks:
  transaction-network:
    name: transaction-network
    driver: bridge

# delcare a volume to persist data
volumes:
  mongodb-data:
    name: transaction-mongodb-data
